### ISSUE TITLE
org.springframework.http.server.reactive.RequestPath was moved to new package

### ISSUE THREAD

**Issue by siplo** [thymeleaf/thymeleaf-tests#9]
It's not directly yours bug but Spring guys moved class RequestPath to package org.springframework.http.server; commit in github is [here](https://github.com/spring-projects/spring-framework/commit/6855a85c41a51aeb151c8c1103e30a6a6745197b). It means project is not compilable.

**Comment by danielfernandez** [comment]
Fixed now — thanks!
